2022-11-13 00:38:54,551 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 running 'init-local' at Sun, 13 Nov 2022 00:38:54 +0000. Up 11.61 seconds.
2022-11-13 00:38:54,551 - main.py[DEBUG]: No kernel command line url found.
2022-11-13 00:38:54,551 - main.py[DEBUG]: Closing stdin.
2022-11-13 00:38:54,553 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2022-11-13 00:38:54,553 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2022-11-13 00:38:54,553 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2022-11-13 00:38:54,554 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2022-11-13 00:38:54,554 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2022-11-13 00:38:54,554 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2022-11-13 00:38:54,554 - stages.py[DEBUG]: no cache found
2022-11-13 00:38:54,554 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2022-11-13 00:38:54,554 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2022-11-13 00:38:54,616 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 00:38:54,617 - __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2022-11-13 00:38:54,618 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceNoCloud']
2022-11-13 00:38:54,618 - handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
2022-11-13 00:38:54,618 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
2022-11-13 00:38:54,618 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2022-11-13 00:38:54,618 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2022-11-13 00:38:54,618 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
2022-11-13 00:38:54,618 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
2022-11-13 00:38:54,618 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
2022-11-13 00:38:54,618 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
2022-11-13 00:38:54,618 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
2022-11-13 00:38:54,618 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
2022-11-13 00:38:54,618 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
2022-11-13 00:38:54,618 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
2022-11-13 00:38:54,618 - subp.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 00:38:54,624 - subp.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 00:38:54,626 - subp.py[DEBUG]: Running command ['blkid', '-tLABEL=CIDATA', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 00:38:54,627 - subp.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 00:38:54,628 - subp.py[DEBUG]: Running command ['blkid', '-tLABEL_FATBOOT=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 00:38:54,630 - DataSourceNoCloud.py[DEBUG]: Attempting to use data from /dev/sdb
2022-11-13 00:38:54,630 - util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
2022-11-13 00:38:54,630 - util.py[DEBUG]: Read 2235 bytes from /proc/mounts
2022-11-13 00:38:54,630 - util.py[DEBUG]: Fetched {'sysfs': {'fstype': 'sysfs', 'mountpoint': '/sys', 'opts': 'rw,nosuid,nodev,noexec,relatime'}, 'proc': {'fstype': 'proc', 'mountpoint': '/proc', 'opts': 'rw,nosuid,nodev,noexec,relatime'}, 'udev': {'fstype': 'devtmpfs', 'mountpoint': '/dev', 'opts': 'rw,nosuid,relatime,size=1007240k,nr_inodes=251810,mode=755'}, 'devpts': {'fstype': 'devpts', 'mountpoint': '/dev/pts', 'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000'}, 'tmpfs': {'fstype': 'tmpfs', 'mountpoint': '/sys/fs/cgroup', 'opts': 'ro,nosuid,nodev,noexec,mode=755'}, '/dev/sda1': {'fstype': 'ext4', 'mountpoint': '/', 'opts': 'rw,relatime,data=ordered'}, 'securityfs': {'fstype': 'securityfs', 'mountpoint': '/sys/kernel/security', 'opts': 'rw,nosuid,nodev,noexec,relatime'}, 'cgroup': {'fstype': 'cgroup', 'mountpoint': '/sys/fs/cgroup/perf_event', 'opts': 'rw,nosuid,nodev,noexec,relatime,perf_event'}, 'pstore': {'fstype': 'pstore', 'mountpoint': '/sys/fs/pstore', 'opts': 'rw,nosuid,nodev,noexec,relatime'}, 'hugetlbfs': {'fstype': 'hugetlbfs', 'mountpoint': '/dev/hugepages', 'opts': 'rw,relatime,pagesize=2M'}, 'debugfs': {'fstype': 'debugfs', 'mountpoint': '/sys/kernel/debug', 'opts': 'rw,relatime'}, 'systemd-1': {'fstype': 'autofs', 'mountpoint': '/proc/sys/fs/binfmt_misc', 'opts': 'rw,relatime,fd=44,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12012'}, 'mqueue': {'fstype': 'mqueue', 'mountpoint': '/dev/mqueue', 'opts': 'rw,relatime'}, 'configfs': {'fstype': 'configfs', 'mountpoint': '/sys/kernel/config', 'opts': 'rw,relatime'}, 'fusectl': {'fstype': 'fusectl', 'mountpoint': '/sys/fs/fuse/connections', 'opts': 'rw,relatime'}, 'binfmt_misc': {'fstype': 'binfmt_misc', 'mountpoint': '/proc/sys/fs/binfmt_misc', 'opts': 'rw,relatime'}} mounts from proc
2022-11-13 00:38:54,630 - subp.py[DEBUG]: Running command ['mount', '-o', 'ro', '-t', 'auto', '/dev/sdb', '/run/cloud-init/tmp/tmpb6c_k9p_'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:54,639 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpb6c_k9p_//user-data (quiet=False)
2022-11-13 00:38:54,639 - util.py[DEBUG]: Read 42 bytes from /run/cloud-init/tmp/tmpb6c_k9p_//user-data
2022-11-13 00:38:54,639 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpb6c_k9p_//meta-data (quiet=False)
2022-11-13 00:38:54,639 - util.py[DEBUG]: Read 64 bytes from /run/cloud-init/tmp/tmpb6c_k9p_//meta-data
2022-11-13 00:38:54,639 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpb6c_k9p_//vendor-data (quiet=False)
2022-11-13 00:38:54,639 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpb6c_k9p_//network-config (quiet=False)
2022-11-13 00:38:54,639 - subp.py[DEBUG]: Running command ['umount', '/run/cloud-init/tmp/tmpb6c_k9p_'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:54,659 - util.py[DEBUG]: Attempting to load yaml from string of length 64 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,660 - DataSourceNoCloud.py[DEBUG]: Using data from /dev/sdb
2022-11-13 00:38:54,661 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-nocloud - wb: [644] 8 bytes
2022-11-13 00:38:54,661 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-nocloud'
2022-11-13 00:38:54,661 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp62f5qcj1) - w: [600] 4843 bytes/chars
2022-11-13 00:38:54,662 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpaxundfct) - w: [644] 1512 bytes/chars
2022-11-13 00:38:54,662 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: found local data from DataSourceNoCloud
2022-11-13 00:38:54,662 - stages.py[INFO]: Loaded datasource DataSourceNoCloud - DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
2022-11-13 00:38:54,662 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 00:38:54,662 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 00:38:54,662 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,670 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 00:38:54,670 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 00:38:54,670 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,671 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 00:38:54,672 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 00:38:54,672 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,674 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 00:38:54,674 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 00:38:54,674 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,674 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,674 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 00:38:54,675 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2022-11-13 00:38:54,675 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-f8a607e19c7c29d1'
2022-11-13 00:38:54,675 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource (quiet=False)
2022-11-13 00:38:54,675 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource - wb: [644] 65 bytes
2022-11-13 00:38:54,676 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 65 bytes
2022-11-13 00:38:54,676 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2022-11-13 00:38:54,676 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2022-11-13 00:38:54,676 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 21 bytes
2022-11-13 00:38:54,676 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 21 bytes
2022-11-13 00:38:54,676 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2022-11-13 00:38:54,677 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 7021 bytes
2022-11-13 00:38:54,677 - main.py[DEBUG]: [local] init will now be targeting instance id: iid-f8a607e19c7c29d1. new=True
2022-11-13 00:38:54,677 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 00:38:54,677 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 00:38:54,677 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,684 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 00:38:54,684 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 00:38:54,684 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,686 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 00:38:54,686 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 00:38:54,686 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,688 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 00:38:54,688 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 00:38:54,688 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,688 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:54,688 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 00:38:54,689 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 00:38:54,689 - cc_set_hostname.py[DEBUG]: Setting the hostname to ubuntu-bionic (ubuntu-bionic)
2022-11-13 00:38:54,690 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2022-11-13 00:38:54,690 - util.py[DEBUG]: Read 7 bytes from /etc/hostname
2022-11-13 00:38:54,690 - util.py[DEBUG]: Writing to /etc/hostname - wb: [644] 14 bytes
2022-11-13 00:38:54,690 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ubuntu-bionic
2022-11-13 00:38:54,690 - subp.py[DEBUG]: Running command ['hostname', 'ubuntu-bionic'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:54,701 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmp4ajzq11w) - w: [644] 59 bytes/chars
2022-11-13 00:38:54,701 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 00:38:54,701 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 00:38:54,701 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:54,701 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:54,701 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 00:38:54,701 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/name_assign_type (quiet=False)
2022-11-13 00:38:54,702 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/name_assign_type
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/name_assign_type (quiet=False)
2022-11-13 00:38:54,702 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/name_assign_type
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:54,702 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/carrier (quiet=False)
2022-11-13 00:38:54,702 - __init__.py[DEBUG]: Interface has no carrier: enp0s3
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/dormant (quiet=False)
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
2022-11-13 00:38:54,702 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s3/operstate
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 00:38:54,702 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/carrier (quiet=False)
2022-11-13 00:38:54,702 - __init__.py[DEBUG]: Interface has no carrier: enp0s8
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/dormant (quiet=False)
2022-11-13 00:38:54,702 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/operstate (quiet=False)
2022-11-13 00:38:54,702 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s8/operstate
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:54,703 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 00:38:54,703 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:54,703 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 00:38:54,703 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/name_assign_type (quiet=False)
2022-11-13 00:38:54,703 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/name_assign_type
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/name_assign_type (quiet=False)
2022-11-13 00:38:54,703 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/name_assign_type
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:54,703 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/carrier (quiet=False)
2022-11-13 00:38:54,703 - __init__.py[DEBUG]: Interface has no carrier: enp0s3
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/dormant (quiet=False)
2022-11-13 00:38:54,703 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s3/operstate
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/carrier (quiet=False)
2022-11-13 00:38:54,704 - __init__.py[DEBUG]: Interface has no carrier: enp0s8
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/dormant (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/operstate (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s8/operstate
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 00:38:54,704 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2022-11-13 00:38:54,704 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/addr_assign_type (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/addr_assign_type
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/uevent (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s3/uevent
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/addr_assign_type (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/addr_assign_type
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/uevent (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s8/uevent
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/device/device (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s8/device/device
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/type (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/type
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/type (quiet=False)
2022-11-13 00:38:54,705 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/type
2022-11-13 00:38:54,705 - networking.py[DEBUG]: net: all expected physical devices present
2022-11-13 00:38:54,705 - stages.py[DEBUG]: applying net config names for {'ethernets': {'enp0s3': {'dhcp4': True, 'set-name': 'enp0s3', 'match': {'macaddress': '02:d4:40:b8:a4:a0'}}}, 'version': 2}
2022-11-13 00:38:54,705 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/addr_assign_type (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/addr_assign_type
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/uevent (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s3/uevent
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/addr_assign_type (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/addr_assign_type
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/uevent (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s8/uevent
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 00:38:54,706 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/device/device (quiet=False)
2022-11-13 00:38:54,706 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s8/device/device
2022-11-13 00:38:54,707 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2022-11-13 00:38:54,707 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2022-11-13 00:38:54,707 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
2022-11-13 00:38:54,707 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s3/operstate
2022-11-13 00:38:54,707 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/operstate (quiet=False)
2022-11-13 00:38:54,707 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s8/operstate
2022-11-13 00:38:54,707 - subp.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:54,712 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:54,714 - __init__.py[DEBUG]: Detected interfaces {'lo': {'downable': False, 'device_id': None, 'driver': None, 'mac': '00:00:00:00:00:00', 'name': 'lo', 'up': True}, 'enp0s3': {'downable': True, 'device_id': '0x100e', 'driver': 'e1000', 'mac': '02:d4:40:b8:a4:a0', 'name': 'enp0s3', 'up': False}, 'enp0s8': {'downable': True, 'device_id': '0x100e', 'driver': 'e1000', 'mac': '08:00:27:55:b3:4d', 'name': 'enp0s8', 'up': False}}
2022-11-13 00:38:54,714 - __init__.py[DEBUG]: no work necessary for renaming of [['02:d4:40:b8:a4:a0', 'enp0s3', 'e1000', '0x100e']]
2022-11-13 00:38:54,715 - stages.py[INFO]: Applying network configuration from fallback bringup=False: {'ethernets': {'enp0s3': {'dhcp4': True, 'set-name': 'enp0s3', 'match': {'macaddress': '02:d4:40:b8:a4:a0'}}}, 'version': 2}
2022-11-13 00:38:54,715 - util.py[DEBUG]: Writing to /run/cloud-init/sem/apply_network_config.once - wb: [644] 24 bytes
2022-11-13 00:38:54,717 - __init__.py[DEBUG]: Selected renderer 'netplan' from priority list: None
2022-11-13 00:38:54,717 - network_state.py[DEBUG]: Passthrough netplan v2 config
2022-11-13 00:38:54,717 - netplan.py[DEBUG]: V2 to V2 passthrough
2022-11-13 00:38:54,718 - util.py[DEBUG]: Writing to /etc/netplan/50-cloud-init.yaml - wb: [644] 485 bytes
2022-11-13 00:38:54,718 - subp.py[DEBUG]: Running command ['netplan', 'generate'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:54,806 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:54,809 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/enp0s3'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:54,811 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/enp0s8'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:54,813 - __init__.py[DEBUG]: Not bringing up newly configured network interfaces
2022-11-13 00:38:54,813 - main.py[DEBUG]: [local] Exiting. datasource DataSourceNoCloud [seed=/dev/sdb][dsmode=net] not in local mode.
2022-11-13 00:38:54,813 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmppoep53ze) - w: [644] 518 bytes/chars
2022-11-13 00:38:54,813 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 00:38:54,813 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2022-11-13 00:38:54,814 - util.py[DEBUG]: cloud-init mode 'init' took 0.296 seconds (0.30)
2022-11-13 00:38:54,814 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2022-11-13 00:38:57,251 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 running 'init' at Sun, 13 Nov 2022 00:38:57 +0000. Up 14.31 seconds.
2022-11-13 00:38:57,251 - main.py[DEBUG]: No kernel command line url found.
2022-11-13 00:38:57,251 - main.py[DEBUG]: Closing stdin.
2022-11-13 00:38:57,252 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2022-11-13 00:38:57,253 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2022-11-13 00:38:57,253 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,255 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,257 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2022-11-13 00:38:57,259 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2022-11-13 00:38:57,259 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2022-11-13 00:38:57,260 - util.py[DEBUG]: Read 7021 bytes from /var/lib/cloud/instance/obj.pkl
2022-11-13 00:38:57,261 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2022-11-13 00:38:57,261 - util.py[DEBUG]: Read 21 bytes from /run/cloud-init/.instance-id
2022-11-13 00:38:57,261 - stages.py[DEBUG]: restored from cache with run check: DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
2022-11-13 00:38:57,261 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
2022-11-13 00:38:57,261 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 00:38:57,261 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 00:38:57,261 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,270 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 00:38:57,270 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 00:38:57,270 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,271 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 00:38:57,271 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 00:38:57,271 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,273 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 00:38:57,273 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 00:38:57,273 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,274 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,274 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 00:38:57,274 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2022-11-13 00:38:57,275 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-f8a607e19c7c29d1'
2022-11-13 00:38:57,275 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource (quiet=False)
2022-11-13 00:38:57,275 - util.py[DEBUG]: Read 65 bytes from /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource
2022-11-13 00:38:57,275 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource - wb: [644] 65 bytes
2022-11-13 00:38:57,275 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 65 bytes
2022-11-13 00:38:57,276 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2022-11-13 00:38:57,276 - util.py[DEBUG]: Read 21 bytes from /var/lib/cloud/data/instance-id
2022-11-13 00:38:57,276 - stages.py[DEBUG]: previous iid found to be iid-f8a607e19c7c29d1
2022-11-13 00:38:57,276 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 21 bytes
2022-11-13 00:38:57,276 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 21 bytes
2022-11-13 00:38:57,276 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 21 bytes
2022-11-13 00:38:57,277 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 7047 bytes
2022-11-13 00:38:57,277 - main.py[DEBUG]: [net] init will now be targeting instance id: iid-f8a607e19c7c29d1. new=False
2022-11-13 00:38:57,277 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 00:38:57,277 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 00:38:57,277 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,285 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 00:38:57,285 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 00:38:57,285 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,286 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 00:38:57,286 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 00:38:57,286 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,289 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 00:38:57,289 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 00:38:57,289 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,289 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,289 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 00:38:57,290 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 00:38:57,290 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 00:38:57,290 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:57,290 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:57,290 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 00:38:57,290 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 00:38:57,291 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 00:38:57,291 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/name_assign_type (quiet=False)
2022-11-13 00:38:57,291 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/name_assign_type
2022-11-13 00:38:57,291 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/name_assign_type (quiet=False)
2022-11-13 00:38:57,291 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/name_assign_type
2022-11-13 00:38:57,291 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:57,291 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:57,291 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/carrier (quiet=False)
2022-11-13 00:38:57,291 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/carrier
2022-11-13 00:38:57,291 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 00:38:57,292 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 00:38:57,292 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/carrier (quiet=False)
2022-11-13 00:38:57,292 - __init__.py[DEBUG]: Interface has no carrier: enp0s8
2022-11-13 00:38:57,292 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/dormant (quiet=False)
2022-11-13 00:38:57,292 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/operstate (quiet=False)
2022-11-13 00:38:57,292 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s8/operstate
2022-11-13 00:38:57,292 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:57,292 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:57,292 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2022-11-13 00:38:57,293 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=boot-legacy
2022-11-13 00:38:57,293 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update allowed
2022-11-13 00:38:57,293 - stages.py[DEBUG]: applying net config names for {'ethernets': {'enp0s3': {'dhcp4': True, 'set-name': 'enp0s3', 'match': {'macaddress': '02:d4:40:b8:a4:a0'}}}, 'version': 2}
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 00:38:57,293 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2022-11-13 00:38:57,293 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2022-11-13 00:38:57,293 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 00:38:57,293 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 00:38:57,293 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/addr_assign_type (quiet=False)
2022-11-13 00:38:57,293 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/addr_assign_type
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/uevent (quiet=False)
2022-11-13 00:38:57,293 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s3/uevent
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 00:38:57,293 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 00:38:57,293 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 00:38:57,293 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/addr_assign_type (quiet=False)
2022-11-13 00:38:57,294 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/addr_assign_type
2022-11-13 00:38:57,294 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/uevent (quiet=False)
2022-11-13 00:38:57,294 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s8/uevent
2022-11-13 00:38:57,294 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 00:38:57,294 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 00:38:57,294 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/device/device (quiet=False)
2022-11-13 00:38:57,294 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s8/device/device
2022-11-13 00:38:57,294 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2022-11-13 00:38:57,294 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2022-11-13 00:38:57,294 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
2022-11-13 00:38:57,294 - util.py[DEBUG]: Read 3 bytes from /sys/class/net/enp0s3/operstate
2022-11-13 00:38:57,294 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/operstate (quiet=False)
2022-11-13 00:38:57,294 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s8/operstate
2022-11-13 00:38:57,294 - subp.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,296 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,297 - __init__.py[DEBUG]: Detected interfaces {'lo': {'downable': False, 'device_id': None, 'driver': None, 'mac': '00:00:00:00:00:00', 'name': 'lo', 'up': True}, 'enp0s3': {'downable': False, 'device_id': '0x100e', 'driver': 'e1000', 'mac': '02:d4:40:b8:a4:a0', 'name': 'enp0s3', 'up': True}, 'enp0s8': {'downable': True, 'device_id': '0x100e', 'driver': 'e1000', 'mac': '08:00:27:55:b3:4d', 'name': 'enp0s8', 'up': False}}
2022-11-13 00:38:57,297 - __init__.py[DEBUG]: no work necessary for renaming of [['02:d4:40:b8:a4:a0', 'enp0s3', 'e1000', '0x100e']]
2022-11-13 00:38:57,298 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2022-11-13 00:38:57,298 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2022-11-13 00:38:57,298 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/user-data.txt - wb: [600] 42 bytes
2022-11-13 00:38:57,298 - util.py[DEBUG]: Attempting to load yaml from string of length 42 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,300 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/user-data.txt.i - wb: [600] 347 bytes
2022-11-13 00:38:57,300 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/vendor-data.txt - wb: [600] 0 bytes
2022-11-13 00:38:57,301 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/vendor-data.txt.i - wb: [600] 308 bytes
2022-11-13 00:38:57,301 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/vendor-data2.txt - wb: [600] 0 bytes
2022-11-13 00:38:57,302 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/vendor-data2.txt.i - wb: [600] 308 bytes
2022-11-13 00:38:57,303 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2022-11-13 00:38:57,303 - util.py[DEBUG]: Read 59 bytes from /var/lib/cloud/data/set-hostname
2022-11-13 00:38:57,303 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2022-11-13 00:38:57,303 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/consume_data - wb: [644] 24 bytes
2022-11-13 00:38:57,303 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/consume_data'>)
2022-11-13 00:38:57,303 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2022-11-13 00:38:57,304 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2022-11-13 00:38:57,304 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2022-11-13 00:38:57,304 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2022-11-13 00:38:57,304 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2022-11-13 00:38:57,304 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2022-11-13 00:38:57,304 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2022-11-13 00:38:57,304 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2022-11-13 00:38:57,304 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2022-11-13 00:38:57,304 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,304 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,304 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,304 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,304 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,304 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2022-11-13 00:38:57,304 - __init__.py[DEBUG]: {'MIME-Version': '1.0', 'Content-Type': 'text/cloud-config', 'Content-Disposition': 'attachment; filename="part-001"'}
2022-11-13 00:38:57,304 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, part-001, 3) with frequency once-per-instance
2022-11-13 00:38:57,304 - util.py[DEBUG]: Attempting to load yaml from string of length 42 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,305 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2022-11-13 00:38:57,305 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2022-11-13 00:38:57,305 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/cloud-config.txt - wb: [600] 78 bytes
2022-11-13 00:38:57,305 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,305 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,306 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,306 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,306 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2022-11-13 00:38:57,306 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2022-11-13 00:38:57,306 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2022-11-13 00:38:57,306 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2022-11-13 00:38:57,306 - stages.py[DEBUG]: no vendordata from datasource
2022-11-13 00:38:57,306 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2022-11-13 00:38:57,306 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2022-11-13 00:38:57,306 - stages.py[DEBUG]: no vendordata2 from datasource
2022-11-13 00:38:57,306 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2022-11-13 00:38:57,306 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 00:38:57,306 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 00:38:57,306 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,314 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 00:38:57,314 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 00:38:57,314 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,315 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 00:38:57,315 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 00:38:57,315 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,318 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 00:38:57,318 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 00:38:57,318 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,318 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,318 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 00:38:57,318 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2022-11-13 00:38:57,318 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/instance/cloud-config.txt
2022-11-13 00:38:57,319 - util.py[DEBUG]: Attempting to load yaml from string of length 78 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,319 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,319 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,322 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2022-11-13 00:38:57,323 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/instance/cloud-config.txt
2022-11-13 00:38:57,323 - util.py[DEBUG]: Attempting to load yaml from string of length 78 with allowed root types (<class 'dict'>,)
2022-11-13 00:38:57,324 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2022-11-13 00:38:57,324 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 9837 bytes
2022-11-13 00:38:57,325 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2022-11-13 00:38:57,325 - main.py[DEBUG]: no di_report found in config.
2022-11-13 00:38:57,326 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,326 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,327 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,328 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,329 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,329 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,331 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,331 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,334 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,334 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,336 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,336 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,338 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,338 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,340 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,340 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,342 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,342 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,343 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,344 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,345 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,345 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,346 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,346 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,349 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,349 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,351 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:38:57,351 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:38:57,353 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 00:38:57,353 - modules.py[INFO]: Skipping modules 'bootcmd,write-files,disk_setup,ca-certs,rsyslog' because no applicable config is provided.
2022-11-13 00:38:57,354 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2022-11-13 00:38:57,354 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2022-11-13 00:38:57,354 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7fc3de0f7208>)
2022-11-13 00:38:57,354 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2022-11-13 00:38:57,354 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2022-11-13 00:38:57,354 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2022-11-13 00:38:57,355 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2022-11-13 00:38:57,355 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_seed_random - wb: [644] 24 bytes
2022-11-13 00:38:57,355 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_seed_random'>)
2022-11-13 00:38:57,355 - cc_seed_random.py[DEBUG]: no command provided
2022-11-13 00:38:57,355 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2022-11-13 00:38:57,355 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2022-11-13 00:38:57,355 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2022-11-13 00:38:57,355 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fc3de0f2a90>)
2022-11-13 00:38:57,355 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2022-11-13 00:38:57,355 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,359 - util.py[DEBUG]: Reading from /proc/726/mountinfo (quiet=False)
2022-11-13 00:38:57,359 - util.py[DEBUG]: Read 2965 bytes from /proc/726/mountinfo
2022-11-13 00:38:57,359 - util.py[DEBUG]: Reading from /sys/class/block/sda1/partition (quiet=False)
2022-11-13 00:38:57,359 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/sda1/partition
2022-11-13 00:38:57,359 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:14.0/host2/target2:0:0/2:0:0:0/block/sda/dev (quiet=False)
2022-11-13 00:38:57,359 - util.py[DEBUG]: Read 4 bytes from /sys/devices/pci0000:00/0000:00:14.0/host2/target2:0:0/2:0:0:0/block/sda/dev
2022-11-13 00:38:57,359 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/sda', '1'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,394 - subp.py[DEBUG]: Running command ['growpart', '/dev/sda', '1'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,418 - util.py[DEBUG]: resize_devices took 0.059 seconds
2022-11-13 00:38:57,418 - cc_growpart.py[INFO]: '/' resized: changed (/dev/sda, 1) from 2359296000 to 42948607488
2022-11-13 00:38:57,418 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2022-11-13 00:38:57,418 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2022-11-13 00:38:57,418 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2022-11-13 00:38:57,419 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7fc3de0bb9e8>)
2022-11-13 00:38:57,419 - util.py[DEBUG]: Reading from /proc/726/mountinfo (quiet=False)
2022-11-13 00:38:57,419 - util.py[DEBUG]: Read 2965 bytes from /proc/726/mountinfo
2022-11-13 00:38:57,419 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/sda1 mnt_point=/ path=/
2022-11-13 00:38:57,419 - cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/sda1
2022-11-13 00:38:57,419 - subp.py[DEBUG]: Running command ('resize2fs', '/dev/sda1') with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,623 - util.py[DEBUG]: Resizing took 0.204 seconds
2022-11-13 00:38:57,624 - cc_resizefs.py[DEBUG]: Resized root filesystem (type=ext4, val=True)
2022-11-13 00:38:57,624 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2022-11-13 00:38:57,624 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2022-11-13 00:38:57,624 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2022-11-13 00:38:57,624 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_mounts - wb: [644] 24 bytes
2022-11-13 00:38:57,625 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_mounts'>)
2022-11-13 00:38:57,625 - cc_mounts.py[DEBUG]: mounts configuration is []
2022-11-13 00:38:57,625 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2022-11-13 00:38:57,625 - util.py[DEBUG]: Read 43 bytes from /etc/fstab
2022-11-13 00:38:57,625 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2022-11-13 00:38:57,625 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2022-11-13 00:38:57,625 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2022-11-13 00:38:57,625 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2022-11-13 00:38:57,625 - cc_mounts.py[DEBUG]: changed default device swap => None
2022-11-13 00:38:57,625 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2022-11-13 00:38:57,625 - cc_mounts.py[DEBUG]: no need to setup swap
2022-11-13 00:38:57,625 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2022-11-13 00:38:57,625 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2022-11-13 00:38:57,625 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2022-11-13 00:38:57,625 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2022-11-13 00:38:57,625 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_set_hostname - wb: [644] 24 bytes
2022-11-13 00:38:57,626 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_set_hostname'>)
2022-11-13 00:38:57,626 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2022-11-13 00:38:57,626 - util.py[DEBUG]: Read 59 bytes from /var/lib/cloud/data/set-hostname
2022-11-13 00:38:57,626 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2022-11-13 00:38:57,626 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2022-11-13 00:38:57,626 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2022-11-13 00:38:57,626 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2022-11-13 00:38:57,626 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fc3de0f2780>)
2022-11-13 00:38:57,626 - cc_update_hostname.py[DEBUG]: Updating hostname to ubuntu-bionic (ubuntu-bionic)
2022-11-13 00:38:57,626 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2022-11-13 00:38:57,626 - util.py[DEBUG]: Read 14 bytes from /etc/hostname
2022-11-13 00:38:57,626 - __init__.py[DEBUG]: Attempting to update hostname to ubuntu-bionic in 1 files
2022-11-13 00:38:57,626 - util.py[DEBUG]: Reading from /var/lib/cloud/data/previous-hostname (quiet=False)
2022-11-13 00:38:57,626 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 14 bytes
2022-11-13 00:38:57,627 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2022-11-13 00:38:57,627 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2022-11-13 00:38:57,627 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2022-11-13 00:38:57,627 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7fc3de06a438>)
2022-11-13 00:38:57,627 - cc_update_etc_hosts.py[DEBUG]: Managing localhost in /etc/hosts
2022-11-13 00:38:57,627 - util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
2022-11-13 00:38:57,628 - util.py[DEBUG]: Read 221 bytes from /etc/hosts
2022-11-13 00:38:57,628 - util.py[DEBUG]: Writing to /etc/hosts - wb: [644] 260 bytes
2022-11-13 00:38:57,628 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2022-11-13 00:38:57,628 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2022-11-13 00:38:57,628 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2022-11-13 00:38:57,628 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_users_groups - wb: [644] 24 bytes
2022-11-13 00:38:57,628 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_users_groups'>)
2022-11-13 00:38:57,629 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2022-11-13 00:38:57,629 - util.py[DEBUG]: Read 386 bytes from /etc/os-release
2022-11-13 00:38:57,629 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2022-11-13 00:38:57,629 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2022-11-13 00:38:57,629 - __init__.py[DEBUG]: Adding user ubuntu
2022-11-13 00:38:57,630 - subp.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,audio,cdrom,dialout,dip,floppy,lxd,netdev,plugdev,sudo,video', '--shell', '/bin/bash', '-m']
2022-11-13 00:38:57,783 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ubuntu'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,813 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2022-11-13 00:38:57,823 - util.py[DEBUG]: Read 755 bytes from /etc/sudoers
2022-11-13 00:38:57,824 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 141 bytes
2022-11-13 00:38:57,824 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2022-11-13 00:38:57,824 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2022-11-13 00:38:57,824 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2022-11-13 00:38:57,824 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_ssh - wb: [644] 23 bytes
2022-11-13 00:38:57,825 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_ssh'>)
2022-11-13 00:38:57,825 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,924 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2022-11-13 00:38:57,924 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,987 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2022-11-13 00:38:57,987 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,990 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2022-11-13 00:38:57,991 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:38:57,994 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2022-11-13 00:38:57,994 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_rsa_key.pub (quiet=False)
2022-11-13 00:38:57,994 - util.py[DEBUG]: Read 400 bytes from /etc/ssh/ssh_host_rsa_key.pub
2022-11-13 00:38:57,994 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2022-11-13 00:38:57,994 - util.py[DEBUG]: Read 180 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2022-11-13 00:38:57,995 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2022-11-13 00:38:57,995 - util.py[DEBUG]: Read 100 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2022-11-13 00:38:57,995 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2022-11-13 00:38:57,996 - util.py[DEBUG]: Read 3262 bytes from /etc/ssh/sshd_config
2022-11-13 00:38:57,996 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh to 1001:1001
2022-11-13 00:38:57,996 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 0 bytes
2022-11-13 00:38:57,996 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh/authorized_keys to 1001:1001
2022-11-13 00:38:57,996 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2022-11-13 00:38:57,996 - util.py[DEBUG]: Read 0 bytes from /home/ubuntu/.ssh/authorized_keys
2022-11-13 00:38:57,997 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 0 bytes
2022-11-13 00:38:57,999 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2022-11-13 00:38:58,000 - util.py[DEBUG]: Read 3262 bytes from /etc/ssh/sshd_config
2022-11-13 00:38:58,000 - util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
2022-11-13 00:38:58,000 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2022-11-13 00:38:58,000 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2022-11-13 00:38:58,000 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2022-11-13 00:38:58,000 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2022-11-13 00:38:58,000 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2022-11-13 00:38:58,001 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2022-11-13 00:38:58,001 - main.py[DEBUG]: Ran 10 modules with 0 failures
2022-11-13 00:38:58,001 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpqfa41svv) - w: [644] 545 bytes/chars
2022-11-13 00:38:58,001 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 00:38:58,001 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2022-11-13 00:38:58,001 - util.py[DEBUG]: cloud-init mode 'init' took 0.784 seconds (0.78)
2022-11-13 00:38:58,001 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2022-11-13 00:39:02,227 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 running 'modules:config' at Sun, 13 Nov 2022 00:39:02 +0000. Up 19.26 seconds.
2022-11-13 00:39:02,228 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,229 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,233 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,233 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,235 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,235 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,236 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,236 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,237 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,238 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,239 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,239 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,240 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,240 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,242 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,242 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,243 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,243 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,246 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,246 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,248 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,248 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,250 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,250 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,251 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,251 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,253 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,253 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,254 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,254 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,255 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:02,255 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:02,256 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 00:39:02,257 - modules.py[INFO]: Skipping modules 'wireguard,snap,ubuntu_autoinstall,keyboard,apt-pipelining,ubuntu-advantage,ntp,timezone,disable-ec2-metadata,runcmd' because no applicable config is provided.
2022-11-13 00:39:02,258 - modules.py[DEBUG]: Running module ssh-import-id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2022-11-13 00:39:02,258 - handlers.py[DEBUG]: start: modules-config/config-ssh-import-id: running config-ssh-import-id with frequency once-per-instance
2022-11-13 00:39:02,258 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_ssh_import_id - wb: [644] 25 bytes
2022-11-13 00:39:02,258 - helpers.py[DEBUG]: Running config-ssh-import-id using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_ssh_import_id'>)
2022-11-13 00:39:02,258 - cc_ssh_import_id.py[DEBUG]: Skipping module named ssh-import-id, no 'ssh_import_id' directives found.
2022-11-13 00:39:02,258 - handlers.py[DEBUG]: finish: modules-config/config-ssh-import-id: SUCCESS: config-ssh-import-id ran successfully
2022-11-13 00:39:02,258 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2022-11-13 00:39:02,259 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2022-11-13 00:39:02,259 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_locale - wb: [644] 25 bytes
2022-11-13 00:39:02,259 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_locale'>)
2022-11-13 00:39:02,259 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2022-11-13 00:39:02,259 - util.py[DEBUG]: Read 13 bytes from /etc/default/locale
2022-11-13 00:39:02,259 - cc_locale.py[DEBUG]: Setting locale to C.UTF-8
2022-11-13 00:39:02,259 - debian.py[DEBUG]: System has 'LANG=C.UTF-8' requested 'C.UTF-8', skipping regeneration.
2022-11-13 00:39:02,259 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2022-11-13 00:39:02,259 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2022-11-13 00:39:02,259 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2022-11-13 00:39:02,259 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_set_passwords - wb: [644] 25 bytes
2022-11-13 00:39:02,260 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_set_passwords'>)
2022-11-13 00:39:02,260 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'ssh'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:39:02,265 - cc_set_passwords.py[DEBUG]: Leaving SSH config 'PasswordAuthentication' unchanged. ssh_pwauth=None
2022-11-13 00:39:02,265 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2022-11-13 00:39:02,265 - modules.py[DEBUG]: Running module grub-dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2022-11-13 00:39:02,265 - handlers.py[DEBUG]: start: modules-config/config-grub-dpkg: running config-grub-dpkg with frequency once-per-instance
2022-11-13 00:39:02,265 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_grub_dpkg - wb: [644] 25 bytes
2022-11-13 00:39:02,266 - helpers.py[DEBUG]: Running config-grub-dpkg using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_grub_dpkg'>)
2022-11-13 00:39:02,266 - subp.py[DEBUG]: Running command ['grub-probe', '-t', 'disk', '/boot'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:39:02,301 - subp.py[DEBUG]: Running command ['udevadm', 'info', '--root', '--query=symlink', '/dev/sda'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:39:02,303 - cc_grub_dpkg.py[DEBUG]: considering these device symlinks: /dev/disk/by-path/pci-0000:00:14.0-scsi-0:0:0:0
2022-11-13 00:39:02,303 - cc_grub_dpkg.py[DEBUG]: filtered to these disk/by-id symlinks: 
2022-11-13 00:39:02,303 - cc_grub_dpkg.py[DEBUG]: selected /dev/sda
2022-11-13 00:39:02,303 - cc_grub_dpkg.py[DEBUG]: Setting grub debconf-set-selections with '/dev/sda','false'
2022-11-13 00:39:02,303 - subp.py[DEBUG]: Running command ['debconf-set-selections'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:39:02,492 - handlers.py[DEBUG]: finish: modules-config/config-grub-dpkg: SUCCESS: config-grub-dpkg ran successfully
2022-11-13 00:39:02,492 - modules.py[DEBUG]: Running module apt-configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2022-11-13 00:39:02,492 - handlers.py[DEBUG]: start: modules-config/config-apt-configure: running config-apt-configure with frequency once-per-instance
2022-11-13 00:39:02,492 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_apt_configure - wb: [644] 25 bytes
2022-11-13 00:39:02,492 - helpers.py[DEBUG]: Running config-apt-configure using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_apt_configure'>)
2022-11-13 00:39:02,492 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2022-11-13 00:39:02,492 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2022-11-13 00:39:02,492 - util.py[DEBUG]: Read 386 bytes from /etc/os-release
2022-11-13 00:39:02,493 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2022-11-13 00:39:02,493 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2022-11-13 00:39:02,493 - cc_apt_configure.py[DEBUG]: handling apt config: {}
2022-11-13 00:39:02,493 - subp.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:39:02,559 - subp.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:39:02,561 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2022-11-13 00:39:02,561 - cc_apt_configure.py[DEBUG]: got security mirror: None
2022-11-13 00:39:02,562 - subp.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:39:02,564 - util.py[DEBUG]: search for mirror in candidates: '[]'
2022-11-13 00:39:02,564 - util.py[DEBUG]: search for mirror in candidates: '[]'
2022-11-13 00:39:02,564 - __init__.py[DEBUG]: filtered distro mirror info: {'primary': 'http://archive.ubuntu.com/ubuntu', 'security': 'http://security.ubuntu.com/ubuntu'}
2022-11-13 00:39:02,564 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'primary': 'http://archive.ubuntu.com/ubuntu', 'security': 'http://security.ubuntu.com/ubuntu', 'PRIMARY': 'http://archive.ubuntu.com/ubuntu', 'SECURITY': 'http://security.ubuntu.com/ubuntu', 'MIRROR': 'http://archive.ubuntu.com/ubuntu'}
2022-11-13 00:39:02,564 - cc_apt_configure.py[INFO]: No custom template provided, fall back to builtin
2022-11-13 00:39:02,567 - util.py[DEBUG]: Reading from /etc/cloud/templates/sources.list.ubuntu.tmpl (quiet=False)
2022-11-13 00:39:02,567 - util.py[DEBUG]: Read 2858 bytes from /etc/cloud/templates/sources.list.ubuntu.tmpl
2022-11-13 00:39:02,573 - util.py[DEBUG]: Writing to /etc/apt/sources.list - wb: [644] 3142 bytes
2022-11-13 00:39:02,574 - handlers.py[DEBUG]: finish: modules-config/config-apt-configure: SUCCESS: config-apt-configure ran successfully
2022-11-13 00:39:02,574 - modules.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2022-11-13 00:39:02,574 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2022-11-13 00:39:02,574 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_byobu - wb: [644] 25 bytes
2022-11-13 00:39:02,574 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_byobu'>)
2022-11-13 00:39:02,574 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2022-11-13 00:39:02,574 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully
2022-11-13 00:39:02,575 - main.py[DEBUG]: Ran 6 modules with 0 failures
2022-11-13 00:39:02,575 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp8a7rjpi1) - w: [644] 573 bytes/chars
2022-11-13 00:39:02,575 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 00:39:02,575 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2022-11-13 00:39:02,575 - util.py[DEBUG]: cloud-init mode 'modules' took 0.405 seconds (0.41)
2022-11-13 00:39:02,575 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2022-11-13 00:39:02,992 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 running 'modules:final' at Sun, 13 Nov 2022 00:39:02 +0000. Up 20.02 seconds.
2022-11-13 00:39:03,022 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,022 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,024 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,024 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,025 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,025 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,027 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,027 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,029 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,029 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,031 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,031 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,032 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,032 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,034 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,034 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,036 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,036 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,037 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,037 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,039 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,039 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,041 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,041 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,042 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,043 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,044 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,044 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,045 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,045 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,048 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,049 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,050 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,050 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,051 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,051 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,052 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,053 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,054 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,054 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,055 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,055 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,057 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,057 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,058 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 00:39:03,058 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 00:39:03,059 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 00:39:03,061 - modules.py[INFO]: Skipping modules 'package-update-upgrade-install,fan,landscape,lxd,ubuntu-drivers,write-files-deferred,puppet,chef,ansible,mcollective,salt-minion,phone-home,power-state-change' because no applicable config is provided.
2022-11-13 00:39:03,061 - modules.py[DEBUG]: Running module reset_rmc (<module 'cloudinit.config.cc_reset_rmc' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_reset_rmc.py'>) with frequency once-per-instance
2022-11-13 00:39:03,061 - handlers.py[DEBUG]: start: modules-final/config-reset_rmc: running config-reset_rmc with frequency once-per-instance
2022-11-13 00:39:03,062 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_reset_rmc - wb: [644] 25 bytes
2022-11-13 00:39:03,062 - helpers.py[DEBUG]: Running config-reset_rmc using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_reset_rmc'>)
2022-11-13 00:39:03,062 - cc_reset_rmc.py[DEBUG]: module disabled, RSCT_PATH not present
2022-11-13 00:39:03,062 - handlers.py[DEBUG]: finish: modules-final/config-reset_rmc: SUCCESS: config-reset_rmc ran successfully
2022-11-13 00:39:03,062 - modules.py[DEBUG]: Running module refresh_rmc_and_interface (<module 'cloudinit.config.cc_refresh_rmc_and_interface' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_refresh_rmc_and_interface.py'>) with frequency always
2022-11-13 00:39:03,062 - handlers.py[DEBUG]: start: modules-final/config-refresh_rmc_and_interface: running config-refresh_rmc_and_interface with frequency always
2022-11-13 00:39:03,062 - helpers.py[DEBUG]: Running config-refresh_rmc_and_interface using lock (<cloudinit.helpers.DummyLock object at 0x7fe3f3976320>)
2022-11-13 00:39:03,062 - cc_refresh_rmc_and_interface.py[DEBUG]: No 'rmcctrl' in path, disabled
2022-11-13 00:39:03,063 - handlers.py[DEBUG]: finish: modules-final/config-refresh_rmc_and_interface: SUCCESS: config-refresh_rmc_and_interface ran successfully
2022-11-13 00:39:03,063 - modules.py[DEBUG]: Running module rightscale_userdata (<module 'cloudinit.config.cc_rightscale_userdata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rightscale_userdata.py'>) with frequency once-per-instance
2022-11-13 00:39:03,063 - handlers.py[DEBUG]: start: modules-final/config-rightscale_userdata: running config-rightscale_userdata with frequency once-per-instance
2022-11-13 00:39:03,063 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_rightscale_userdata - wb: [644] 24 bytes
2022-11-13 00:39:03,063 - helpers.py[DEBUG]: Running config-rightscale_userdata using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_rightscale_userdata'>)
2022-11-13 00:39:03,063 - cc_rightscale_userdata.py[DEBUG]: Failed to get raw userdata in module rightscale_userdata
2022-11-13 00:39:03,063 - handlers.py[DEBUG]: finish: modules-final/config-rightscale_userdata: SUCCESS: config-rightscale_userdata ran successfully
2022-11-13 00:39:03,063 - modules.py[DEBUG]: Running module scripts-vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2022-11-13 00:39:03,063 - handlers.py[DEBUG]: start: modules-final/config-scripts-vendor: running config-scripts-vendor with frequency once-per-instance
2022-11-13 00:39:03,063 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_scripts_vendor - wb: [644] 25 bytes
2022-11-13 00:39:03,063 - helpers.py[DEBUG]: Running config-scripts-vendor using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_scripts_vendor'>)
2022-11-13 00:39:03,064 - handlers.py[DEBUG]: finish: modules-final/config-scripts-vendor: SUCCESS: config-scripts-vendor ran successfully
2022-11-13 00:39:03,064 - modules.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2022-11-13 00:39:03,064 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
2022-11-13 00:39:03,064 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 25 bytes
2022-11-13 00:39:03,064 - helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2022-11-13 00:39:03,064 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
2022-11-13 00:39:03,064 - modules.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2022-11-13 00:39:03,064 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
2022-11-13 00:39:03,064 - helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7fe3f3976908>)
2022-11-13 00:39:03,064 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
2022-11-13 00:39:03,064 - modules.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2022-11-13 00:39:03,064 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
2022-11-13 00:39:03,064 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_scripts_per_instance - wb: [644] 24 bytes
2022-11-13 00:39:03,065 - helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_scripts_per_instance'>)
2022-11-13 00:39:03,065 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
2022-11-13 00:39:03,065 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2022-11-13 00:39:03,065 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2022-11-13 00:39:03,065 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_scripts_user - wb: [644] 25 bytes
2022-11-13 00:39:03,065 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_scripts_user'>)
2022-11-13 00:39:03,065 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2022-11-13 00:39:03,065 - modules.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2022-11-13 00:39:03,065 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2022-11-13 00:39:03,065 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_ssh_authkey_fingerprints - wb: [644] 24 bytes
2022-11-13 00:39:03,066 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_ssh_authkey_fingerprints'>)
2022-11-13 00:39:03,066 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2022-11-13 00:39:03,066 - util.py[DEBUG]: Read 3262 bytes from /etc/ssh/sshd_config
2022-11-13 00:39:03,066 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2022-11-13 00:39:03,067 - util.py[DEBUG]: Read 0 bytes from /home/ubuntu/.ssh/authorized_keys
2022-11-13 00:39:03,081 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2022-11-13 00:39:03,081 - modules.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2022-11-13 00:39:03,081 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2022-11-13 00:39:03,081 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_keys_to_console - wb: [644] 24 bytes
2022-11-13 00:39:03,082 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_keys_to_console'>)
2022-11-13 00:39:03,082 - subp.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 00:39:03,157 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2022-11-13 00:39:03,157 - modules.py[DEBUG]: Running module install-hotplug (<module 'cloudinit.config.cc_install_hotplug' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_install_hotplug.py'>) with frequency once-per-instance
2022-11-13 00:39:03,157 - handlers.py[DEBUG]: start: modules-final/config-install-hotplug: running config-install-hotplug with frequency once-per-instance
2022-11-13 00:39:03,157 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_install_hotplug - wb: [644] 25 bytes
2022-11-13 00:39:03,158 - helpers.py[DEBUG]: Running config-install-hotplug using lock (<FileLock using file '/var/lib/cloud/instances/iid-f8a607e19c7c29d1/sem/config_install_hotplug'>)
2022-11-13 00:39:03,158 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2022-11-13 00:39:03,158 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=hotplug
2022-11-13 00:39:03,158 - cc_install_hotplug.py[DEBUG]: Skipping hotplug install, not enabled
2022-11-13 00:39:03,158 - handlers.py[DEBUG]: finish: modules-final/config-install-hotplug: SUCCESS: config-install-hotplug ran successfully
2022-11-13 00:39:03,158 - modules.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2022-11-13 00:39:03,158 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2022-11-13 00:39:03,158 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7fe3f395e160>)
2022-11-13 00:39:03,158 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 00:39:03,159 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2022-11-13 00:39:03,162 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 finished at Sun, 13 Nov 2022 00:39:03 +0000. Datasource DataSourceNoCloud [seed=/dev/sdb][dsmode=net].  Up 20.23 seconds
2022-11-13 00:39:03,162 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 69 bytes
2022-11-13 00:39:03,162 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2022-11-13 00:39:03,162 - main.py[DEBUG]: Ran 12 modules with 0 failures
2022-11-13 00:39:03,163 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp1dw_xjgw) - w: [644] 600 bytes/chars
2022-11-13 00:39:03,163 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp9jcodu7y) - w: [644] 96 bytes/chars
2022-11-13 00:39:03,163 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2022-11-13 00:39:03,163 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 00:39:03,163 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2022-11-13 00:39:03,163 - util.py[DEBUG]: cloud-init mode 'modules' took 0.244 seconds (0.25)
2022-11-13 00:39:03,163 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
2022-11-13 17:13:11,867 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 running 'init-local' at Sun, 13 Nov 2022 17:13:11 +0000. Up 8.02 seconds.
2022-11-13 17:13:11,875 - main.py[DEBUG]: No kernel command line url found.
2022-11-13 17:13:11,875 - main.py[DEBUG]: Closing stdin.
2022-11-13 17:13:11,877 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2022-11-13 17:13:11,877 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2022-11-13 17:13:11,878 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2022-11-13 17:13:11,878 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2022-11-13 17:13:11,878 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2022-11-13 17:13:11,879 - util.py[DEBUG]: Read 9837 bytes from /var/lib/cloud/instance/obj.pkl
2022-11-13 17:13:11,882 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
2022-11-13 17:13:11,882 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
2022-11-13 17:13:11,882 - stages.py[DEBUG]: cache invalid in datasource: DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
2022-11-13 17:13:11,882 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: cache invalid in datasource: DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
2022-11-13 17:13:11,882 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2022-11-13 17:13:11,883 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 17:13:11,883 - __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2022-11-13 17:13:11,884 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceNoCloud']
2022-11-13 17:13:11,884 - handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
2022-11-13 17:13:11,884 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
2022-11-13 17:13:11,884 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2022-11-13 17:13:11,884 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2022-11-13 17:13:11,884 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
2022-11-13 17:13:11,884 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
2022-11-13 17:13:11,884 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
2022-11-13 17:13:11,884 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
2022-11-13 17:13:11,884 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
2022-11-13 17:13:11,884 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
2022-11-13 17:13:11,884 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
2022-11-13 17:13:11,884 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
2022-11-13 17:13:11,884 - subp.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 17:13:11,890 - subp.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 17:13:11,891 - subp.py[DEBUG]: Running command ['blkid', '-tLABEL=CIDATA', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 17:13:11,893 - subp.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 17:13:11,895 - subp.py[DEBUG]: Running command ['blkid', '-tLABEL_FATBOOT=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2022-11-13 17:13:11,896 - DataSourceNoCloud.py[DEBUG]: Attempting to use data from /dev/sdb
2022-11-13 17:13:11,896 - util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
2022-11-13 17:13:11,896 - util.py[DEBUG]: Read 2235 bytes from /proc/mounts
2022-11-13 17:13:11,897 - util.py[DEBUG]: Fetched {'sysfs': {'fstype': 'sysfs', 'mountpoint': '/sys', 'opts': 'rw,nosuid,nodev,noexec,relatime'}, 'proc': {'fstype': 'proc', 'mountpoint': '/proc', 'opts': 'rw,nosuid,nodev,noexec,relatime'}, 'udev': {'fstype': 'devtmpfs', 'mountpoint': '/dev', 'opts': 'rw,nosuid,relatime,size=1007240k,nr_inodes=251810,mode=755'}, 'devpts': {'fstype': 'devpts', 'mountpoint': '/dev/pts', 'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000'}, 'tmpfs': {'fstype': 'tmpfs', 'mountpoint': '/sys/fs/cgroup', 'opts': 'ro,nosuid,nodev,noexec,mode=755'}, '/dev/sda1': {'fstype': 'ext4', 'mountpoint': '/', 'opts': 'rw,relatime,data=ordered'}, 'securityfs': {'fstype': 'securityfs', 'mountpoint': '/sys/kernel/security', 'opts': 'rw,nosuid,nodev,noexec,relatime'}, 'cgroup': {'fstype': 'cgroup', 'mountpoint': '/sys/fs/cgroup/blkio', 'opts': 'rw,nosuid,nodev,noexec,relatime,blkio'}, 'pstore': {'fstype': 'pstore', 'mountpoint': '/sys/fs/pstore', 'opts': 'rw,nosuid,nodev,noexec,relatime'}, 'systemd-1': {'fstype': 'autofs', 'mountpoint': '/proc/sys/fs/binfmt_misc', 'opts': 'rw,relatime,fd=38,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=11608'}, 'mqueue': {'fstype': 'mqueue', 'mountpoint': '/dev/mqueue', 'opts': 'rw,relatime'}, 'debugfs': {'fstype': 'debugfs', 'mountpoint': '/sys/kernel/debug', 'opts': 'rw,relatime'}, 'hugetlbfs': {'fstype': 'hugetlbfs', 'mountpoint': '/dev/hugepages', 'opts': 'rw,relatime,pagesize=2M'}, 'configfs': {'fstype': 'configfs', 'mountpoint': '/sys/kernel/config', 'opts': 'rw,relatime'}, 'fusectl': {'fstype': 'fusectl', 'mountpoint': '/sys/fs/fuse/connections', 'opts': 'rw,relatime'}, 'binfmt_misc': {'fstype': 'binfmt_misc', 'mountpoint': '/proc/sys/fs/binfmt_misc', 'opts': 'rw,relatime'}} mounts from proc
2022-11-13 17:13:11,897 - subp.py[DEBUG]: Running command ['mount', '-o', 'ro', '-t', 'auto', '/dev/sdb', '/run/cloud-init/tmp/tmpkq5dsaia'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:11,905 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpkq5dsaia//user-data (quiet=False)
2022-11-13 17:13:11,905 - util.py[DEBUG]: Read 42 bytes from /run/cloud-init/tmp/tmpkq5dsaia//user-data
2022-11-13 17:13:11,905 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpkq5dsaia//meta-data (quiet=False)
2022-11-13 17:13:11,906 - util.py[DEBUG]: Read 64 bytes from /run/cloud-init/tmp/tmpkq5dsaia//meta-data
2022-11-13 17:13:11,906 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpkq5dsaia//vendor-data (quiet=False)
2022-11-13 17:13:11,906 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpkq5dsaia//network-config (quiet=False)
2022-11-13 17:13:11,906 - subp.py[DEBUG]: Running command ['umount', '/run/cloud-init/tmp/tmpkq5dsaia'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:11,923 - util.py[DEBUG]: Attempting to load yaml from string of length 64 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,924 - DataSourceNoCloud.py[DEBUG]: Using data from /dev/sdb
2022-11-13 17:13:11,925 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-nocloud - wb: [644] 8 bytes
2022-11-13 17:13:11,925 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-nocloud'
2022-11-13 17:13:11,926 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmphfft2fix) - w: [600] 4885 bytes/chars
2022-11-13 17:13:11,926 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmp2mxyii0m) - w: [644] 1519 bytes/chars
2022-11-13 17:13:11,926 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: found local data from DataSourceNoCloud
2022-11-13 17:13:11,926 - stages.py[INFO]: Loaded datasource DataSourceNoCloud - DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
2022-11-13 17:13:11,926 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 17:13:11,926 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 17:13:11,926 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,935 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 17:13:11,935 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 17:13:11,935 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,936 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 17:13:11,936 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 17:13:11,936 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,938 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 17:13:11,939 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 17:13:11,939 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,939 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,939 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 17:13:11,939 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2022-11-13 17:13:11,939 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-f8a607e19c7c29d1'
2022-11-13 17:13:11,940 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource (quiet=False)
2022-11-13 17:13:11,940 - util.py[DEBUG]: Read 65 bytes from /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource
2022-11-13 17:13:11,940 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource - wb: [644] 65 bytes
2022-11-13 17:13:11,941 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 65 bytes
2022-11-13 17:13:11,941 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2022-11-13 17:13:11,941 - util.py[DEBUG]: Read 21 bytes from /var/lib/cloud/data/instance-id
2022-11-13 17:13:11,941 - stages.py[DEBUG]: previous iid found to be iid-f8a607e19c7c29d1
2022-11-13 17:13:11,942 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 21 bytes
2022-11-13 17:13:11,942 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 21 bytes
2022-11-13 17:13:11,942 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 21 bytes
2022-11-13 17:13:11,942 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 7066 bytes
2022-11-13 17:13:11,943 - main.py[DEBUG]: [local] init will now be targeting instance id: iid-f8a607e19c7c29d1. new=False
2022-11-13 17:13:11,943 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 17:13:11,943 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 17:13:11,943 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,951 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 17:13:11,951 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 17:13:11,951 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,952 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 17:13:11,952 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 17:13:11,952 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,954 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 17:13:11,955 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 17:13:11,955 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,955 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,955 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 17:13:11,955 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2022-11-13 17:13:11,955 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/instance/cloud-config.txt
2022-11-13 17:13:11,955 - util.py[DEBUG]: Attempting to load yaml from string of length 78 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:11,956 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 17:13:11,957 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2022-11-13 17:13:11,957 - util.py[DEBUG]: Read 59 bytes from /var/lib/cloud/data/set-hostname
2022-11-13 17:13:11,957 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2022-11-13 17:13:11,957 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 17:13:11,957 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 17:13:11,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 17:13:11,958 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 17:13:11,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 17:13:11,958 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 17:13:11,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/name_assign_type (quiet=False)
2022-11-13 17:13:11,958 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/name_assign_type
2022-11-13 17:13:11,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/name_assign_type (quiet=False)
2022-11-13 17:13:11,958 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/name_assign_type
2022-11-13 17:13:11,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 17:13:11,958 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 17:13:11,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/carrier (quiet=False)
2022-11-13 17:13:11,958 - __init__.py[DEBUG]: Interface has no carrier: enp0s3
2022-11-13 17:13:11,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/dormant (quiet=False)
2022-11-13 17:13:11,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
2022-11-13 17:13:11,958 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s3/operstate
2022-11-13 17:13:11,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 17:13:11,958 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 17:13:11,959 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/carrier (quiet=False)
2022-11-13 17:13:11,959 - __init__.py[DEBUG]: Interface has no carrier: enp0s8
2022-11-13 17:13:11,959 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/dormant (quiet=False)
2022-11-13 17:13:11,959 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/operstate (quiet=False)
2022-11-13 17:13:11,959 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s8/operstate
2022-11-13 17:13:11,959 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 17:13:11,959 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 17:13:11,960 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2022-11-13 17:13:11,960 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=boot
2022-11-13 17:13:11,960 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2022-11-13 17:13:11,960 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=boot-legacy
2022-11-13 17:13:11,960 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update allowed
2022-11-13 17:13:11,960 - stages.py[DEBUG]: applying net config names for {'ethernets': {'enp0s3': {'dhcp4': True, 'set-name': 'enp0s3', 'match': {'macaddress': '02:d4:40:b8:a4:a0'}}}, 'version': 2}
2022-11-13 17:13:11,960 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 17:13:11,960 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 17:13:11,960 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2022-11-13 17:13:11,960 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2022-11-13 17:13:11,960 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2022-11-13 17:13:11,960 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2022-11-13 17:13:11,960 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 17:13:11,960 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 17:13:11,961 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/addr_assign_type (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/addr_assign_type
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/uevent (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s3/uevent
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/addr_assign_type (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/addr_assign_type
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/uevent (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s8/uevent
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/device/device (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s8/device/device
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
2022-11-13 17:13:11,961 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s3/operstate
2022-11-13 17:13:11,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/operstate (quiet=False)
2022-11-13 17:13:11,962 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s8/operstate
2022-11-13 17:13:11,962 - subp.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:11,971 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:11,973 - __init__.py[DEBUG]: Detected interfaces {'lo': {'downable': False, 'device_id': None, 'driver': None, 'mac': '00:00:00:00:00:00', 'name': 'lo', 'up': True}, 'enp0s3': {'downable': True, 'device_id': '0x100e', 'driver': 'e1000', 'mac': '02:d4:40:b8:a4:a0', 'name': 'enp0s3', 'up': False}, 'enp0s8': {'downable': True, 'device_id': '0x100e', 'driver': 'e1000', 'mac': '08:00:27:55:b3:4d', 'name': 'enp0s8', 'up': False}}
2022-11-13 17:13:11,973 - __init__.py[DEBUG]: no work necessary for renaming of [['02:d4:40:b8:a4:a0', 'enp0s3', 'e1000', '0x100e']]
2022-11-13 17:13:11,973 - main.py[DEBUG]: [local] Exiting. datasource DataSourceNoCloud [seed=/dev/sdb][dsmode=net] not in local mode.
2022-11-13 17:13:11,973 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpk3tp2pen) - w: [644] 517 bytes/chars
2022-11-13 17:13:11,974 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 17:13:11,974 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2022-11-13 17:13:11,974 - util.py[DEBUG]: cloud-init mode 'init' took 0.143 seconds (0.14)
2022-11-13 17:13:11,974 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2022-11-13 17:13:15,902 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 running 'init' at Sun, 13 Nov 2022 17:13:15 +0000. Up 12.05 seconds.
2022-11-13 17:13:15,902 - main.py[DEBUG]: No kernel command line url found.
2022-11-13 17:13:15,902 - main.py[DEBUG]: Closing stdin.
2022-11-13 17:13:15,904 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2022-11-13 17:13:15,904 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2022-11-13 17:13:15,904 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:15,907 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:15,910 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2022-11-13 17:13:15,914 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2022-11-13 17:13:15,914 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2022-11-13 17:13:15,914 - util.py[DEBUG]: Read 7066 bytes from /var/lib/cloud/instance/obj.pkl
2022-11-13 17:13:15,916 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2022-11-13 17:13:15,916 - util.py[DEBUG]: Read 21 bytes from /run/cloud-init/.instance-id
2022-11-13 17:13:15,916 - stages.py[DEBUG]: restored from cache with run check: DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
2022-11-13 17:13:15,916 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
2022-11-13 17:13:15,916 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 17:13:15,916 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 17:13:15,916 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,927 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 17:13:15,927 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 17:13:15,927 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,929 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 17:13:15,929 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 17:13:15,929 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,932 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 17:13:15,932 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 17:13:15,932 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,932 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,932 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 17:13:15,933 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2022-11-13 17:13:15,933 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/instance/cloud-config.txt
2022-11-13 17:13:15,933 - util.py[DEBUG]: Attempting to load yaml from string of length 78 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,934 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2022-11-13 17:13:15,936 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-f8a607e19c7c29d1'
2022-11-13 17:13:15,936 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource (quiet=False)
2022-11-13 17:13:15,936 - util.py[DEBUG]: Read 65 bytes from /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource
2022-11-13 17:13:15,937 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/datasource - wb: [644] 65 bytes
2022-11-13 17:13:15,937 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 65 bytes
2022-11-13 17:13:15,937 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2022-11-13 17:13:15,937 - util.py[DEBUG]: Read 21 bytes from /var/lib/cloud/data/instance-id
2022-11-13 17:13:15,937 - stages.py[DEBUG]: previous iid found to be iid-f8a607e19c7c29d1
2022-11-13 17:13:15,938 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 21 bytes
2022-11-13 17:13:15,938 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 21 bytes
2022-11-13 17:13:15,938 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 21 bytes
2022-11-13 17:13:15,939 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 7092 bytes
2022-11-13 17:13:15,940 - main.py[DEBUG]: [net] init will now be targeting instance id: iid-f8a607e19c7c29d1. new=False
2022-11-13 17:13:15,940 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 17:13:15,940 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 17:13:15,940 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,950 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 17:13:15,950 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 17:13:15,950 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,951 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 17:13:15,951 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 17:13:15,952 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,955 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 17:13:15,955 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 17:13:15,955 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,955 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,955 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 17:13:15,956 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2022-11-13 17:13:15,956 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/instance/cloud-config.txt
2022-11-13 17:13:15,956 - util.py[DEBUG]: Attempting to load yaml from string of length 78 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,957 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 17:13:15,957 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 17:13:15,957 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 17:13:15,957 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 17:13:15,957 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 17:13:15,957 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 17:13:15,958 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 17:13:15,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/name_assign_type (quiet=False)
2022-11-13 17:13:15,958 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/name_assign_type
2022-11-13 17:13:15,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/name_assign_type (quiet=False)
2022-11-13 17:13:15,958 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/name_assign_type
2022-11-13 17:13:15,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 17:13:15,958 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 17:13:15,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/carrier (quiet=False)
2022-11-13 17:13:15,958 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/carrier
2022-11-13 17:13:15,958 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 17:13:15,958 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 17:13:15,959 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/carrier (quiet=False)
2022-11-13 17:13:15,959 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/carrier
2022-11-13 17:13:15,959 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 17:13:15,959 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 17:13:15,959 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2022-11-13 17:13:15,959 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=boot
2022-11-13 17:13:15,960 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2022-11-13 17:13:15,960 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=boot-legacy
2022-11-13 17:13:15,960 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update allowed
2022-11-13 17:13:15,960 - stages.py[DEBUG]: applying net config names for {'ethernets': {'enp0s3': {'dhcp4': True, 'set-name': 'enp0s3', 'match': {'macaddress': '02:d4:40:b8:a4:a0'}}}, 'version': 2}
2022-11-13 17:13:15,960 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 17:13:15,960 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 17:13:15,960 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2022-11-13 17:13:15,960 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2022-11-13 17:13:15,960 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2022-11-13 17:13:15,960 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2022-11-13 17:13:15,960 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2022-11-13 17:13:15,960 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2022-11-13 17:13:15,960 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2022-11-13 17:13:15,960 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2022-11-13 17:13:15,960 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/addr_assign_type (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/addr_assign_type
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/uevent (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s3/uevent
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/addr_assign_type (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s8/addr_assign_type
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/uevent (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s8/uevent
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s8/address
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/device/device (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s8/device/device
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
2022-11-13 17:13:15,961 - util.py[DEBUG]: Read 3 bytes from /sys/class/net/enp0s3/operstate
2022-11-13 17:13:15,961 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/operstate (quiet=False)
2022-11-13 17:13:15,962 - util.py[DEBUG]: Read 3 bytes from /sys/class/net/enp0s8/operstate
2022-11-13 17:13:15,962 - subp.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:15,964 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:15,967 - __init__.py[DEBUG]: Detected interfaces {'lo': {'downable': False, 'device_id': None, 'driver': None, 'mac': '00:00:00:00:00:00', 'name': 'lo', 'up': True}, 'enp0s3': {'downable': False, 'device_id': '0x100e', 'driver': 'e1000', 'mac': '02:d4:40:b8:a4:a0', 'name': 'enp0s3', 'up': True}, 'enp0s8': {'downable': False, 'device_id': '0x100e', 'driver': 'e1000', 'mac': '08:00:27:55:b3:4d', 'name': 'enp0s8', 'up': True}}
2022-11-13 17:13:15,967 - __init__.py[DEBUG]: no work necessary for renaming of [['02:d4:40:b8:a4:a0', 'enp0s3', 'e1000', '0x100e']]
2022-11-13 17:13:15,967 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2022-11-13 17:13:15,968 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2022-11-13 17:13:15,968 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/user-data.txt - wb: [600] 42 bytes
2022-11-13 17:13:15,969 - util.py[DEBUG]: Attempting to load yaml from string of length 42 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,970 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/user-data.txt.i - wb: [600] 347 bytes
2022-11-13 17:13:15,971 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/vendor-data.txt - wb: [600] 0 bytes
2022-11-13 17:13:15,971 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/vendor-data.txt.i - wb: [600] 308 bytes
2022-11-13 17:13:15,972 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/vendor-data2.txt - wb: [600] 0 bytes
2022-11-13 17:13:15,973 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/vendor-data2.txt.i - wb: [600] 308 bytes
2022-11-13 17:13:15,973 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2022-11-13 17:13:15,973 - util.py[DEBUG]: Read 59 bytes from /var/lib/cloud/data/set-hostname
2022-11-13 17:13:15,974 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2022-11-13 17:13:15,974 - helpers.py[DEBUG]: consume_data already ran (freq=once-per-instance)
2022-11-13 17:13:15,974 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2022-11-13 17:13:15,975 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2022-11-13 17:13:15,975 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2022-11-13 17:13:15,975 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2022-11-13 17:13:15,975 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2022-11-13 17:13:15,975 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2022-11-13 17:13:15,975 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2022-11-13 17:13:15,975 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2022-11-13 17:13:15,975 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency always
2022-11-13 17:13:15,975 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency always
2022-11-13 17:13:15,975 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency always
2022-11-13 17:13:15,975 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency always
2022-11-13 17:13:15,976 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency always
2022-11-13 17:13:15,976 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency always
2022-11-13 17:13:15,976 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency always
2022-11-13 17:13:15,976 - __init__.py[DEBUG]: {'MIME-Version': '1.0', 'Content-Type': 'text/cloud-config', 'Content-Disposition': 'attachment; filename="part-001"'}
2022-11-13 17:13:15,976 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, part-001, 3) with frequency always
2022-11-13 17:13:15,976 - util.py[DEBUG]: Attempting to load yaml from string of length 42 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,976 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2022-11-13 17:13:15,976 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency always
2022-11-13 17:13:15,977 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-f8a607e19c7c29d1/cloud-config.txt - wb: [600] 78 bytes
2022-11-13 17:13:15,977 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency always
2022-11-13 17:13:15,977 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency always
2022-11-13 17:13:15,977 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency always
2022-11-13 17:13:15,978 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency always
2022-11-13 17:13:15,978 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency always
2022-11-13 17:13:15,978 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency always
2022-11-13 17:13:15,978 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2022-11-13 17:13:15,978 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2022-11-13 17:13:15,978 - stages.py[DEBUG]: no vendordata from datasource
2022-11-13 17:13:15,978 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2022-11-13 17:13:15,978 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2022-11-13 17:13:15,978 - stages.py[DEBUG]: no vendordata2 from datasource
2022-11-13 17:13:15,978 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2022-11-13 17:13:15,978 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2022-11-13 17:13:15,978 - util.py[DEBUG]: Read 3660 bytes from /etc/cloud/cloud.cfg
2022-11-13 17:13:15,978 - util.py[DEBUG]: Attempting to load yaml from string of length 3660 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,989 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2022-11-13 17:13:15,989 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2022-11-13 17:13:15,989 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,991 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2022-11-13 17:13:15,991 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2022-11-13 17:13:15,991 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,993 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2022-11-13 17:13:15,993 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2022-11-13 17:13:15,994 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,994 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,994 - util.py[DEBUG]: loaded blob returned None, returning default.
2022-11-13 17:13:15,994 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2022-11-13 17:13:15,994 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/instance/cloud-config.txt
2022-11-13 17:13:15,994 - util.py[DEBUG]: Attempting to load yaml from string of length 78 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:15,995 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:15,995 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:15,999 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2022-11-13 17:13:15,999 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/instance/cloud-config.txt
2022-11-13 17:13:15,999 - util.py[DEBUG]: Attempting to load yaml from string of length 78 with allowed root types (<class 'dict'>,)
2022-11-13 17:13:16,001 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2022-11-13 17:13:16,002 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 9882 bytes
2022-11-13 17:13:16,002 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2022-11-13 17:13:16,003 - main.py[DEBUG]: no di_report found in config.
2022-11-13 17:13:16,003 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,004 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,005 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,005 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,007 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,007 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,009 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,009 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,013 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,013 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,016 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,017 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,019 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,020 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,022 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,022 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,024 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,024 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,026 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,026 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,028 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,028 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,030 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,030 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,034 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,034 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,037 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:16,037 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:16,038 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 17:13:16,040 - modules.py[INFO]: Skipping modules 'bootcmd,write-files,disk_setup,ca-certs,rsyslog' because no applicable config is provided.
2022-11-13 17:13:16,040 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2022-11-13 17:13:16,041 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2022-11-13 17:13:16,041 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7fe1cdab57f0>)
2022-11-13 17:13:16,041 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2022-11-13 17:13:16,042 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2022-11-13 17:13:16,042 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2022-11-13 17:13:16,042 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2022-11-13 17:13:16,042 - helpers.py[DEBUG]: config-seed_random already ran (freq=once-per-instance)
2022-11-13 17:13:16,042 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random previously ran
2022-11-13 17:13:16,042 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2022-11-13 17:13:16,043 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2022-11-13 17:13:16,043 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fe1d084ebe0>)
2022-11-13 17:13:16,043 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2022-11-13 17:13:16,043 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:16,053 - util.py[DEBUG]: Reading from /proc/711/mountinfo (quiet=False)
2022-11-13 17:13:16,053 - util.py[DEBUG]: Read 2965 bytes from /proc/711/mountinfo
2022-11-13 17:13:16,053 - util.py[DEBUG]: Reading from /sys/class/block/sda1/partition (quiet=False)
2022-11-13 17:13:16,053 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/sda1/partition
2022-11-13 17:13:16,054 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:14.0/host2/target2:0:0/2:0:0:0/block/sda/dev (quiet=False)
2022-11-13 17:13:16,054 - util.py[DEBUG]: Read 4 bytes from /sys/devices/pci0000:00/0000:00:14.0/host2/target2:0:0/2:0:0:0/block/sda/dev
2022-11-13 17:13:16,054 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/sda', '1'] with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:16,098 - util.py[DEBUG]: resize_devices took 0.045 seconds
2022-11-13 17:13:16,098 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/sda, 1)
2022-11-13 17:13:16,098 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2022-11-13 17:13:16,098 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2022-11-13 17:13:16,099 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2022-11-13 17:13:16,099 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7fe1cd9c5898>)
2022-11-13 17:13:16,099 - util.py[DEBUG]: Reading from /proc/711/mountinfo (quiet=False)
2022-11-13 17:13:16,099 - util.py[DEBUG]: Read 2965 bytes from /proc/711/mountinfo
2022-11-13 17:13:16,099 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/sda1 mnt_point=/ path=/
2022-11-13 17:13:16,099 - cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/sda1
2022-11-13 17:13:16,099 - subp.py[DEBUG]: Running command ('resize2fs', '/dev/sda1') with allowed return codes [0] (shell=False, capture=True)
2022-11-13 17:13:16,103 - util.py[DEBUG]: Resizing took 0.004 seconds
2022-11-13 17:13:16,104 - cc_resizefs.py[DEBUG]: Resized root filesystem (type=ext4, val=True)
2022-11-13 17:13:16,104 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2022-11-13 17:13:16,104 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2022-11-13 17:13:16,104 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2022-11-13 17:13:16,104 - helpers.py[DEBUG]: config-mounts already ran (freq=once-per-instance)
2022-11-13 17:13:16,106 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts previously ran
2022-11-13 17:13:16,106 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2022-11-13 17:13:16,107 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2022-11-13 17:13:16,107 - helpers.py[DEBUG]: config-set_hostname already ran (freq=once-per-instance)
2022-11-13 17:13:16,107 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname previously ran
2022-11-13 17:13:16,107 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2022-11-13 17:13:16,107 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2022-11-13 17:13:16,107 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fe1cdaa6550>)
2022-11-13 17:13:16,107 - cc_update_hostname.py[DEBUG]: Updating hostname to ubuntu-bionic (ubuntu-bionic)
2022-11-13 17:13:16,107 - util.py[DEBUG]: Reading from /var/lib/cloud/data/previous-hostname (quiet=False)
2022-11-13 17:13:16,108 - util.py[DEBUG]: Read 14 bytes from /var/lib/cloud/data/previous-hostname
2022-11-13 17:13:16,108 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2022-11-13 17:13:16,108 - util.py[DEBUG]: Read 14 bytes from /etc/hostname
2022-11-13 17:13:16,108 - __init__.py[DEBUG]: Attempting to update hostname to ubuntu-bionic in 0 files
2022-11-13 17:13:16,108 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2022-11-13 17:13:16,108 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2022-11-13 17:13:16,108 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2022-11-13 17:13:16,108 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7fe1cda62ef0>)
2022-11-13 17:13:16,108 - cc_update_etc_hosts.py[DEBUG]: Managing localhost in /etc/hosts
2022-11-13 17:13:16,108 - util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
2022-11-13 17:13:16,109 - util.py[DEBUG]: Read 260 bytes from /etc/hosts
2022-11-13 17:13:16,109 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2022-11-13 17:13:16,109 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2022-11-13 17:13:16,109 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2022-11-13 17:13:16,109 - helpers.py[DEBUG]: config-users-groups already ran (freq=once-per-instance)
2022-11-13 17:13:16,109 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups previously ran
2022-11-13 17:13:16,109 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2022-11-13 17:13:16,109 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2022-11-13 17:13:16,109 - helpers.py[DEBUG]: config-ssh already ran (freq=once-per-instance)
2022-11-13 17:13:16,110 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh previously ran
2022-11-13 17:13:16,110 - main.py[DEBUG]: Ran 10 modules with 0 failures
2022-11-13 17:13:16,110 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp3f63zf17) - w: [644] 544 bytes/chars
2022-11-13 17:13:16,110 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 17:13:16,110 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2022-11-13 17:13:16,110 - util.py[DEBUG]: cloud-init mode 'init' took 0.252 seconds (0.25)
2022-11-13 17:13:16,110 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2022-11-13 17:13:18,709 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 running 'modules:config' at Sun, 13 Nov 2022 17:13:18 +0000. Up 14.83 seconds.
2022-11-13 17:13:18,723 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,731 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,743 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,743 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,747 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,748 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,769 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,769 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,771 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,771 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,772 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,773 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,774 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,774 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,776 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,776 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,778 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,778 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,781 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,781 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,784 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,784 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,786 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,787 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,788 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,788 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,790 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,790 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,792 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,792 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,793 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:18,793 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:18,794 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 17:13:18,795 - modules.py[INFO]: Skipping modules 'wireguard,snap,ubuntu_autoinstall,keyboard,apt-pipelining,ubuntu-advantage,ntp,timezone,disable-ec2-metadata,runcmd' because no applicable config is provided.
2022-11-13 17:13:18,796 - modules.py[DEBUG]: Running module ssh-import-id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2022-11-13 17:13:18,796 - handlers.py[DEBUG]: start: modules-config/config-ssh-import-id: running config-ssh-import-id with frequency once-per-instance
2022-11-13 17:13:18,796 - helpers.py[DEBUG]: config-ssh-import-id already ran (freq=once-per-instance)
2022-11-13 17:13:18,796 - handlers.py[DEBUG]: finish: modules-config/config-ssh-import-id: SUCCESS: config-ssh-import-id previously ran
2022-11-13 17:13:18,796 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2022-11-13 17:13:18,796 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2022-11-13 17:13:18,796 - helpers.py[DEBUG]: config-locale already ran (freq=once-per-instance)
2022-11-13 17:13:18,796 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale previously ran
2022-11-13 17:13:18,796 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2022-11-13 17:13:18,797 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2022-11-13 17:13:18,797 - helpers.py[DEBUG]: config-set-passwords already ran (freq=once-per-instance)
2022-11-13 17:13:18,797 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords previously ran
2022-11-13 17:13:18,797 - modules.py[DEBUG]: Running module grub-dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2022-11-13 17:13:18,797 - handlers.py[DEBUG]: start: modules-config/config-grub-dpkg: running config-grub-dpkg with frequency once-per-instance
2022-11-13 17:13:18,797 - helpers.py[DEBUG]: config-grub-dpkg already ran (freq=once-per-instance)
2022-11-13 17:13:18,797 - handlers.py[DEBUG]: finish: modules-config/config-grub-dpkg: SUCCESS: config-grub-dpkg previously ran
2022-11-13 17:13:18,797 - modules.py[DEBUG]: Running module apt-configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2022-11-13 17:13:18,797 - handlers.py[DEBUG]: start: modules-config/config-apt-configure: running config-apt-configure with frequency once-per-instance
2022-11-13 17:13:18,797 - helpers.py[DEBUG]: config-apt-configure already ran (freq=once-per-instance)
2022-11-13 17:13:18,797 - handlers.py[DEBUG]: finish: modules-config/config-apt-configure: SUCCESS: config-apt-configure previously ran
2022-11-13 17:13:18,797 - modules.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2022-11-13 17:13:18,797 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2022-11-13 17:13:18,797 - helpers.py[DEBUG]: config-byobu already ran (freq=once-per-instance)
2022-11-13 17:13:18,797 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu previously ran
2022-11-13 17:13:18,797 - main.py[DEBUG]: Ran 6 modules with 0 failures
2022-11-13 17:13:18,798 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpx7zmq5vr) - w: [644] 572 bytes/chars
2022-11-13 17:13:18,798 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 17:13:18,798 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2022-11-13 17:13:18,798 - util.py[DEBUG]: cloud-init mode 'modules' took 0.174 seconds (0.18)
2022-11-13 17:13:18,798 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2022-11-13 17:13:20,168 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 running 'modules:final' at Sun, 13 Nov 2022 17:13:20 +0000. Up 16.30 seconds.
2022-11-13 17:13:20,170 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,170 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,172 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,172 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,174 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,175 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,176 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,176 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,180 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,181 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,184 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,185 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,187 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,187 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,189 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,189 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,191 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,191 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,197 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,197 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,199 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,200 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,202 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,202 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,204 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,204 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,206 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,206 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,209 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,209 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,211 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,211 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,212 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,213 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,214 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,215 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,216 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,216 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,217 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,218 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,219 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,220 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,221 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,221 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,223 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2022-11-13 17:13:20,223 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2022-11-13 17:13:20,224 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2022-11-13 17:13:20,226 - modules.py[INFO]: Skipping modules 'package-update-upgrade-install,fan,landscape,lxd,ubuntu-drivers,write-files-deferred,puppet,chef,ansible,mcollective,salt-minion,phone-home,power-state-change' because no applicable config is provided.
2022-11-13 17:13:20,226 - modules.py[DEBUG]: Running module reset_rmc (<module 'cloudinit.config.cc_reset_rmc' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_reset_rmc.py'>) with frequency once-per-instance
2022-11-13 17:13:20,227 - handlers.py[DEBUG]: start: modules-final/config-reset_rmc: running config-reset_rmc with frequency once-per-instance
2022-11-13 17:13:20,227 - helpers.py[DEBUG]: config-reset_rmc already ran (freq=once-per-instance)
2022-11-13 17:13:20,227 - handlers.py[DEBUG]: finish: modules-final/config-reset_rmc: SUCCESS: config-reset_rmc previously ran
2022-11-13 17:13:20,227 - modules.py[DEBUG]: Running module refresh_rmc_and_interface (<module 'cloudinit.config.cc_refresh_rmc_and_interface' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_refresh_rmc_and_interface.py'>) with frequency always
2022-11-13 17:13:20,227 - handlers.py[DEBUG]: start: modules-final/config-refresh_rmc_and_interface: running config-refresh_rmc_and_interface with frequency always
2022-11-13 17:13:20,227 - helpers.py[DEBUG]: Running config-refresh_rmc_and_interface using lock (<cloudinit.helpers.DummyLock object at 0x7fb13fde4240>)
2022-11-13 17:13:20,227 - cc_refresh_rmc_and_interface.py[DEBUG]: No 'rmcctrl' in path, disabled
2022-11-13 17:13:20,227 - handlers.py[DEBUG]: finish: modules-final/config-refresh_rmc_and_interface: SUCCESS: config-refresh_rmc_and_interface ran successfully
2022-11-13 17:13:20,227 - modules.py[DEBUG]: Running module rightscale_userdata (<module 'cloudinit.config.cc_rightscale_userdata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rightscale_userdata.py'>) with frequency once-per-instance
2022-11-13 17:13:20,227 - handlers.py[DEBUG]: start: modules-final/config-rightscale_userdata: running config-rightscale_userdata with frequency once-per-instance
2022-11-13 17:13:20,227 - helpers.py[DEBUG]: config-rightscale_userdata already ran (freq=once-per-instance)
2022-11-13 17:13:20,227 - handlers.py[DEBUG]: finish: modules-final/config-rightscale_userdata: SUCCESS: config-rightscale_userdata previously ran
2022-11-13 17:13:20,227 - modules.py[DEBUG]: Running module scripts-vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2022-11-13 17:13:20,228 - handlers.py[DEBUG]: start: modules-final/config-scripts-vendor: running config-scripts-vendor with frequency once-per-instance
2022-11-13 17:13:20,228 - helpers.py[DEBUG]: config-scripts-vendor already ran (freq=once-per-instance)
2022-11-13 17:13:20,228 - handlers.py[DEBUG]: finish: modules-final/config-scripts-vendor: SUCCESS: config-scripts-vendor previously ran
2022-11-13 17:13:20,228 - modules.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2022-11-13 17:13:20,228 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
2022-11-13 17:13:20,228 - helpers.py[DEBUG]: config-scripts-per-once already ran (freq=once)
2022-11-13 17:13:20,228 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once previously ran
2022-11-13 17:13:20,228 - modules.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2022-11-13 17:13:20,228 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
2022-11-13 17:13:20,228 - helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7fb13fde4978>)
2022-11-13 17:13:20,229 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
2022-11-13 17:13:20,229 - modules.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2022-11-13 17:13:20,229 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
2022-11-13 17:13:20,229 - helpers.py[DEBUG]: config-scripts-per-instance already ran (freq=once-per-instance)
2022-11-13 17:13:20,229 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance previously ran
2022-11-13 17:13:20,229 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2022-11-13 17:13:20,229 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2022-11-13 17:13:20,229 - helpers.py[DEBUG]: config-scripts-user already ran (freq=once-per-instance)
2022-11-13 17:13:20,229 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user previously ran
2022-11-13 17:13:20,229 - modules.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2022-11-13 17:13:20,229 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2022-11-13 17:13:20,229 - helpers.py[DEBUG]: config-ssh-authkey-fingerprints already ran (freq=once-per-instance)
2022-11-13 17:13:20,229 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints previously ran
2022-11-13 17:13:20,229 - modules.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2022-11-13 17:13:20,229 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2022-11-13 17:13:20,230 - helpers.py[DEBUG]: config-keys-to-console already ran (freq=once-per-instance)
2022-11-13 17:13:20,230 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console previously ran
2022-11-13 17:13:20,230 - modules.py[DEBUG]: Running module install-hotplug (<module 'cloudinit.config.cc_install_hotplug' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_install_hotplug.py'>) with frequency once-per-instance
2022-11-13 17:13:20,230 - handlers.py[DEBUG]: start: modules-final/config-install-hotplug: running config-install-hotplug with frequency once-per-instance
2022-11-13 17:13:20,230 - helpers.py[DEBUG]: config-install-hotplug already ran (freq=once-per-instance)
2022-11-13 17:13:20,230 - handlers.py[DEBUG]: finish: modules-final/config-install-hotplug: SUCCESS: config-install-hotplug previously ran
2022-11-13 17:13:20,230 - modules.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2022-11-13 17:13:20,230 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2022-11-13 17:13:20,230 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7fb13fde45f8>)
2022-11-13 17:13:20,230 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 17:13:20,230 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2022-11-13 17:13:20,234 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1~18.04.1 finished at Sun, 13 Nov 2022 17:13:20 +0000. Datasource DataSourceNoCloud [seed=/dev/sdb][dsmode=net].  Up 16.40 seconds
2022-11-13 17:13:20,234 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 69 bytes
2022-11-13 17:13:20,234 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2022-11-13 17:13:20,234 - main.py[DEBUG]: Ran 12 modules with 0 failures
2022-11-13 17:13:20,234 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpn7pjkv2q) - w: [644] 600 bytes/chars
2022-11-13 17:13:20,235 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpud0ha78e) - w: [644] 96 bytes/chars
2022-11-13 17:13:20,235 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2022-11-13 17:13:20,235 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2022-11-13 17:13:20,235 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2022-11-13 17:13:20,235 - util.py[DEBUG]: cloud-init mode 'modules' took 0.123 seconds (0.12)
2022-11-13 17:13:20,235 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
